name: Test

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 1
      matrix:
        node: [18.x, 20.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Matrix
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}

    - name: Test
      run: |
        npm ci
        npm test
