name: Test

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*'
  pull_request:

jobs:
  test_node:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 1
      matrix:
        node: [12.20.0, 12.x, 14.x, 16.x, 18.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Matrix
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}
        cache: 'npm'

    - name: Test
      run: |
        npm ci
        npm test

  test_deno:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 1
      matrix:
        deno: [1.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'

    - name: Cache Deno
      uses: actions/cache@v3
      with:
        path: ~/.cache/deno
        key: deno-${{ runner.os }}-${{ hashFiles('deno-lock.json') }}
        restore-keys: |
           deno-${{ runner.os }}-${{ hashFiles('deno-lock.json') }}
           deno-${{ runner.os }}-
           deno-

    - name: Setup Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: ${{ matrix.deno }}

    - name: Test
      run: |
        npm ci
        npx denoify
        deno test ./deno/dist/
      env:
        # https://docs.denoify.land/deal-with-github-api-rate-limit-exceeded
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
